source 'https://rubygems.org'
gem "cucumber",				      '3.1.2'
gem "logger", 				      '1.3.0'
gem "page-object", 			    '2.2.6'
gem "rspec", 				        '3.8.0'
gem "selenium-webdriver",   '3.142.0'
gem "parallel_tests", 		  '2.28.0'
gem "require_all", 			    '2.0.0'
gem 'rake', 				        '12.3.2'
gem 'colorize',             '0.8.1'